import{useMemo,useState}from'react';import{bundleMarkdown,repurpose,type Source}from'./domain/repurpose';import AiMode from'./AiMode';
const sample:Source={title:'Do not automate a broken workflow',body:'Automation does not fix a confused process; it makes the confusion move faster. Start by mapping the handoffs, repeated decisions, and waiting time. Once the team agrees on the outcome and owner, use technology to remove low-value effort while keeping judgment visible. The best automation is not the flashiest one—it is the one people trust and actually use.',audience:'operations leaders and B2B founders',tone:'Sharp & practical',cta:'What is one workflow your team should simplify before it automates?'};
function App(){const[source,setSource]=useState<Source>({title:'',body:'',audience:'B2B decision-makers',tone:'Sharp & practical',cta:''});const[active,setActive]=useState(0);const[approved,setApproved]=useState<number[]>([]);const[copied,setCopied]=useState<number|null>(null);const[edits,setEdits]=useState<Record<number,string>>({});const drafts=useMemo(()=>repurpose(source),[source]);const currentDraft=(i:number)=>edits[i]??drafts[i].content;const update=(k:keyof Source,v:string)=>{setSource(x=>({...x,[k]:v}));setEdits({});setApproved([])};const loadSample=()=>{setSource(sample);setEdits({});setApproved([]);setActive(0)};const editDraft=(i:number,value:string)=>{setEdits(x=>({...x,[i]:value}));setApproved(x=>x.filter(value=>value!==i))};async function copy(i:number){await navigator.clipboard.writeText(currentDraft(i));setCopied(i);setTimeout(()=>setCopied(null),1600)}function download(){const editedDrafts=drafts.map((draft,i)=>({...draft,content:currentDraft(i)}));const u=URL.createObjectURL(new Blob([bundleMarkdown(source,editedDrafts)],{type:'text/markdown'}));const a=document.createElement('a');a.href=u;a.download='content-bundle.md';a.click();URL.revokeObjectURL(u)}return <main>
<nav><a href="#top"><i/>PRISM</a><span>One idea / many useful forms</span><button onClick={loadSample}>Load source story</button></nav>
<header id="top"><div className="tag">CONTENT SYSTEM / LAB 07</div><h1>Make one idea<br/><em>travel further.</em></h1><p>Turn a strong source into channel-ready drafts, then review every word before it leaves the studio.</p><div className="orbit"><span>LI</span><span>EM</span><span>SO</span><span>↗</span></div></header>
<AiMode app="content-repurposing-flow" payload={{source,localDrafts:drafts.map((draft,index)=>({...draft,content:currentDraft(index)}))}} label="Repurpose content with AI"/>
<section className="flow"><aside className="source"><div className="source-head"><span>01 / Master source</span><b>{source.body.split(/\s+/).filter(Boolean).length} words</b></div><label>Working title<input value={source.title} onChange={e=>update('title',e.target.value)} placeholder="The single idea"/></label><label>Source text<textarea value={source.body} onChange={e=>update('body',e.target.value)} placeholder="Paste an article, transcript, or point of view…"/></label><div className="two"><label>Audience<input value={source.audience} onChange={e=>update('audience',e.target.value)}/></label><label>Tone<select value={source.tone} onChange={e=>update('tone',e.target.value)}><option>Sharp & practical</option><option>Warm & expert</option><option>Bold & provocative</option></select></label></div><label>Call to action<input value={source.cta} onChange={e=>update('cta',e.target.value)} placeholder="The response you want"/></label><div className="split"><span>1 source</span><i/><span>4 formats</span><i/><span>Human review</span></div></aside>
<div className="outputs"><div className="outputs-head"><span>02 / Channel drafts</span><div>{drafts.map((d,i)=><button className={active===i?'active':''} onClick={()=>setActive(i)} key={d.channel}>{d.channel}<b>{approved.includes(i)?'✓':String(i+1).padStart(2,'0')}</b></button>)}</div></div><article className={`draft draft-${active}`}><div className="draft-top"><div><span>{drafts[active].channel}</span><h2>{drafts[active].label}</h2></div><b>EDITABLE DRAFT</b></div><textarea value={currentDraft(active)} onChange={event=>editDraft(active,event.target.value)} aria-label={`${drafts[active].channel} draft`}/><div className="draft-actions"><button onClick={()=>copy(active)}>{copied===active?'Copied':'Copy draft'}</button><button onClick={()=>setApproved(a=>a.includes(active)?a.filter(x=>x!==active):[...a,active])}>{approved.includes(active)?'Return to review':'Approve draft'} <span>↗</span></button></div></article><div className="queue"><div><span>Review progress</span><b>{approved.length}/4 approved</b></div><div className="meter"><i style={{width:`${approved.length*25}%`}}/></div><button onClick={download}>Download complete bundle ↓</button></div></div></section>
<footer><span>Built by Jamil Darwish</span><span>Draft locally · Review before publishing</span></footer></main>}
export default App;
